project:
  type: website
  output-dir: docs
  render:
  - '*.qmd'
  resources:
  - images/**
website:
  title: Mediterranean Sea
  description: 'Summary Report of Mediterranean Sea In Situ Observations

    '
  navbar:
    logo: images/logo.png
    logo-href: https://aiqc-hub.github.io/aiqc-report/
    right:
    - text: Profile Summary
      menu:
      - text: Summary (MO)
        href: mo_summary.qmd
      - text: Summary (GL)
        href: mo_gl_summary.qmd
      - text: Summary (CORA)
        href: mo_cora_summary.qmd
    - text: Temperature
      menu:
      - text: Temp (MO)
        href: mo_temp.qmd
      - text: Temp (GL)
        href: mo_gl_temp.qmd
      - text: Temp (CORA)
        href: mo_cora_temp.qmd
      - text: '---'
      - text: Temp QC (MO)
        href: mo_temp_qc.qmd
      - text: Temp QC (GL)
        href: mo_gl_temp_qc.qmd
      - text: Temp QC (CORA)
        href: mo_cora_temp_qc.qmd
    - text: Salinity
      menu:
      - text: Psal (MO)
        href: mo_psal.qmd
      - text: Psal (GL)
        href: mo_gl_psal.qmd
      - text: Psal (CORA)
        href: mo_cora_psal.qmd
      - text: '---'
      - text: Psal QC (MO)
        href: mo_psal_qc.qmd
      - text: Psal QC (GL)
        href: mo_gl_psal_qc.qmd
      - text: Psal QC (CORA)
        href: mo_cora_psal_qc.qmd
format:
  html:
    toc: true
    toc-depth: 2
