---
title: "Profile Summary (CORA)"
description: |
  Profile summary report generated from a single Parquet file has been created from over 10000 NetCDF files from the CORA In-situ observations.
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
r_func_path <- "./_func"
r_funcs <- c("libraries.Rmd", "common.Rmd", "common_mo_cora.Rmd", "summary_common.Rmd")
```

```{r, import, child=file.path(r_func_path, r_funcs)}
```

```{r, location_filtering1, include = FALSE}
src <- knitr::knit_expand(t_location_filtering, df=df_name, df_filtered=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
```

## 1. Basic Information
```{r, basic_info, results = 'asis'}
res <- knitr::knit_expand(t_s_basic_info)
cat(res, sep = '\n')
```

---

## 2. Descriptive Statistics of `r region_code1` CTD Data
```{r, descriptive_stats, results = 'asis'}
src <- knitr::knit_expand(t_s_descriptive_stats, df=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 3. Locations
```{r, locations, results = 'asis'}
src <- knitr::knit_expand(t_s_locations, plot_nrow=2, plot_height=10)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 4. Distribution of Profiles Over Time
```{r, distribution_time, results = 'asis'}
src <- knitr::knit_expand(t_s_distribution_time, plot_nrow=2, plot_height=10)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 5. Duplicate Profiles Within Platforms
```{r, duplicate_within, results = 'asis'}
src <- knitr::knit_expand(t_s_duplicate_within, df=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

```{r, duplicate_details1, results = 'asis'}
src <- knitr::knit_expand(t_s_duplicate_within_details, df=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 6. Duplicate Profiles Across Platforms
```{r, duplicate_across, results = 'asis'}
src <- knitr::knit_expand(t_s_duplicate_across, df=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

```{r, duplicate_details2, results = 'asis'}
src <- knitr::knit_expand(t_s_duplicate_across_details, df=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 7. Observation Counts By Profile
```{r, observation_counts, results = 'asis'}
src <- knitr::knit_expand(t_s_observation_counts, plot_nrow=2, plot_height=10)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

```{r, cleanup, include = FALSE}
rm(list = ls())
```
