---
title: "Pressure QC (GL)"
description: |
  Basic analysis of the pressure QC data from the Mediterranean Sea in situ NRT observations.
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r include = FALSE}
knitr::opts_chunk$set(echo=FALSE)

# Common functions
r_func_path <- "./_func"
r_funcs <- c("libraries.Rmd", "common.Rmd", "common_mo_gl.Rmd", "qc.Rmd")

# Variables
var <- "pres"
qc_var <- "pres_qc"
qc_var_name <- "Pressure QC flag"
```

```{r, import, child=file.path(r_func_path, r_funcs)}
```

```{r, load_qc_summary, include = FALSE}
src <- knitr::knit_expand(t_load_qc_summary)
res <- knitr::knit_child(text = src, quiet = TRUE)
```

```{r, location_filtering, include = FALSE}
src <- knitr::knit_expand(t_location_filtering, df=df_name, df_filtered=df_filtered_name,
                          df_qc1=df_qc1_name, df_qc1_filtered=df_qc1_filtered_name,
                          df_qc4=df_qc4_name, df_qc4_filtered=df_qc4_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
```

## 1. Basic Information
```{r, basic_info, results = 'asis'}
res <- knitr::knit_expand(t_qc_basic_info)
cat(res, sep = '\n')
```

---

## 2. Summary Statistics
```{r, summary_stats, results = 'asis'}
src <- knitr::knit_expand(t_qc_summary_stats, df=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 3. Distributions Over Time
```{r, distributions, results = 'asis'}
src <- knitr::knit_expand(t_qc_distributions, df=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 4. Fraction of QC4 Flags per Profile
```{r, fraction, results = 'asis'}
src <- knitr::knit_expand(t_qc_qc4_proportion, df=df_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

```{r, cleanup, include = FALSE}
rm(list = ls())
```
