---
title: "NRT (MO) vs CORA"
description: |
  Basic analysis of the temperature QC data from the Arctic Ocean in situ NRT observations.
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r, init, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)

# Common functions
r_func_path <- "./_func"
r_funcs <- c("libraries.Rmd", "common.Rmd", "common_mo.Rmd", "summary_common.Rmd", "comp.Rmd", "qc.Rmd")
r_cora_common <- "common_mo_cora.Rmd"
```

```{r, import, include = FALSE, child=file.path(r_func_path, r_funcs)}
```

```{r, copy_nrt_df, include = FALSE}
src <- knitr::knit_expand(t_comp_copy_df, df_new_name="df_nrt", df_orig_name=df_name)
res <- knitr::knit_child(text = src, quiet = TRUE)

basic_info_nrt <- knitr::knit_expand(t_comp_basic_info_item)
```

```{r, import, include = FALSE, child=file.path(r_func_path, r_cora_common)}
```

```{r, copy_cora_df, include = FALSE}
src <- knitr::knit_expand(t_comp_copy_df, df_new_name="df_cora", df_orig_name=df_name)
res <- knitr::knit_child(text = src, quiet = TRUE)

basic_info_cora <- knitr::knit_expand(t_comp_basic_info_item)
```

## 1. Basic Information

```{r, basic_info, results = 'asis'}
src <- knitr::knit_expand(t_comp_basic_info)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 2. NRT and CORA counts

```{r, nrt_cora_df_counts, results = 'asis'}
src <- knitr::knit_expand(t_comp_df_counts, df_nrt="df_nrt", df_cora="df_cora")
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 3. Intersection between NRT and CORA

```{r, nrt_cora_intersection, results = 'asis'}
src <- knitr::knit_expand(t_comp_intersection, df_nrt="df_nrt", df_cora="df_cora")
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 4. QC Flag Counts (Strict Criteria)

```{r, nrt_cora_qc_flag_counts, results = 'asis'}
src <- knitr::knit_expand(t_comp_qc_counts, df_nrt="df_nrt", df_cora="df_cora")
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

```{r, cleanup, include = FALSE}
rm(list = ls())
```
