---
title: "Pressure (AR)"
description: |
  Basic analysis of the pressure data from the Mediterranean Sea in situ NRT observations.
---

```{r, init, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)

# Common functions
library(reportlib)
r_func_path <- "./_func"
r_funcs <- c("common_site.Rmd", "common_mo.Rmd")

# Variables
var <- "pres"
var_name <- "Pressure"
var_label <- "Pres"
```

```{r, import, include = FALSE, child=file.path(r_func_path, r_funcs)}
```

```{r, load_qc_summary, include = FALSE}
src <- knitr::knit_expand(template_path("load_qc_summary.Rmd"))
res <- knitr::knit_child(text = src, quiet = TRUE)
```

```{r, location_filtering, include = FALSE}
src <- knitr::knit_expand(template_path("location_filtering.Rmd"), df=df_name, df_filtered=df_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
```

```{r, location_filtering_qc, include = FALSE}
src <- knitr::knit_expand(template_path("location_filtering_qc.Rmd"),
                          f_qc1=df_qc1_name, df_qc1_filtered=df_qc1_filtered_name,
                          df_qc4=df_qc4_name, df_qc4_filtered=df_qc4_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
```

## 1. Basic Information
```{r, basic_info, results = 'asis'}
src <- knitr::knit_expand(template_path("var_basic_info.Rmd"))
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 2. Summary Statistics
```{r, summary_stats, results = 'asis'}
src <- knitr::knit_expand(template_path("var_summary_stats.Rmd"), df=df_filtered_name,
                          df_qc1=df_qc1_filtered_name, df_qc4=df_qc4_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 3. Distributions By Year
```{r, distributions_year, results = 'asis'}
src <- knitr::knit_expand(template_path("var_distribution_year.Rmd"))
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 4. Distributions By Month
```{r, distributions_month, results = 'asis'}
src <- knitr::knit_expand(template_path("var_distribution_month.Rmd"))
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

```{r, cleanup, include = FALSE}
rm(list = ls())
```
