---
title: "Practical Salinity (AR)"
description: |
  Basic analysis of the salinity data from the Mediterranean Sea in situ NRT observations.
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r, init, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)

# Common functions
r_func_path <- "./_func"
r_funcs <- c("libraries.Rmd", "common.Rmd", "common_mo.Rmd", "var.Rmd")

# Variables
var <- "psal"
var_name <- "Practical salinity"
var_label <- "Psal"
```

```{r, import, include = FALSE, child=file.path(r_func_path, r_funcs)}
```

```{r, load_qc_summary, include = FALSE}
src <- knitr::knit_expand(t_load_qc_summary)
res <- knitr::knit_child(text = src, quiet = TRUE)
```

```{r, location_filtering, include = FALSE}
src <- knitr::knit_expand(t_location_filtering, df=df_name, df_filtered=df_filtered_name,
                          df_qc1=df_qc1_name, df_qc1_filtered=df_qc1_filtered_name,
                          df_qc4=df_qc4_name, df_qc4_filtered=df_qc4_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
```

## 1. Basic Information
```{r, basic_info, results = 'asis'}
src <- knitr::knit_expand(t_v_basic_info)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 2. Summary Statistics
```{r, summary_stats, results = 'asis'}
src <- knitr::knit_expand(t_v_summary_stats, df=df_filtered_name,
                          df_qc1=df_qc1_filtered_name, df_qc4=df_qc4_filtered_name)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 3. Distributions By Year
```{r, distributions_year, results = 'asis'}
src <- knitr::knit_expand(t_v_distributions_year)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## 4. Distributions By Month
```{r, distributions_month, results = 'asis'}
src <- knitr::knit_expand(t_v_distributions_month)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

```{r, cleanup, include = FALSE}
rm(list = ls())
```
