```{r, df_distinct_dfs, echo = FALSE, message = FALSE, warning = FALSE}

df_nrt_strict_distinct <- distinct_profiles_by_common_uniq_ids(df_nrt_strict, uniq_id_strict)

df_cora_strict <- filter_df_by_common_ids(df_cora_with_uniq_ids, uniq_ids_strict)
df_cora_strict_distinct <- distinct_profiles_by_common_uniq_ids(df_cora_strict, uniq_id_strict)

```

::: {.panelset}
::: {.panel}

### Pressure

#### QC flag counts (NRT)

```{r, pres_qc_counts1, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
nrt_flags <- get_flag_counts(df_nrt_strict_distinct, "pres_qc")
kbl_table(nrt_flags) %>% kable_styling(font_size = 12)
```

<br>

#### QC flag counts (CORA)

```{r, pres_qc_counts2, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
cora_flags <- get_flag_counts(df_cora_strict_distinct, "pres_qc")
kbl_table(cora_flags) %>% kable_styling(font_size = 12)
```

:::

::: {.panel}

### Temperature

#### QC flag counts (NRT)

```{r, pres_qc_counts3, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
nrt_flags <- get_flag_counts(df_nrt_strict_distinct, "temp_qc")
kbl_table(nrt_flags) %>% kable_styling(font_size = 12)
```

<br>

#### QC flag counts (CORA)

```{r, pres_qc_counts4, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
cora_flags <- get_flag_counts(df_cora_strict_distinct, "temp_qc")
kbl_table(cora_flags) %>% kable_styling(font_size = 12)
```

:::

::: {.panel}

### Salinity

#### QC flag counts (NRT)

```{r, pres_qc_counts5, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
nrt_flags <- get_flag_counts(df_nrt_strict_distinct, "psal_qc")
kbl_table(nrt_flags) %>% kable_styling(font_size = 12)
```

<br>

#### QC flag counts (CORA)

```{r, pres_qc_counts6, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
cora_flags <- get_flag_counts(df_cora_strict_distinct, "psal_qc")
kbl_table(cora_flags) %>% kable_styling(font_size = 12)
```

:::
:::