### Location ranges

 - **Longitude**: `r round(min(summary_loc_table[, "Min(Lon)"]), 3)` to `r round(max(summary_loc_table[, "Max(Lon)"]), 3)`
 - **Latitude**: `r round(min(summary_loc_table[, "Min(Lat)"]), 3)` to `r round(max(summary_loc_table[, "Max(Lat)"]), 3)`


### Locations by profiles

```{r, t_summary_loc1, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
loc_table_cols <- c("Min(Lon)", "Max(Lon)", "Diff(Lon)",
                    "Min(Lat)" ,"Max(Lat)", "Diff(Lat)")
create_dt_summary_tab(summary_loc_table, cols=loc_table_cols)

```

### Mapped locations of all profiles and three selected platforms

```{r, t_summary_loc2, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = {{plot_height}}}
lat_range <- range(summary_table_netcdf$latitude)
lon_range <- range(summary_table_netcdf$longitude)

p_long_x_lat <- summary_table_netcdf %>%
 create_region_scatter("Scatter plot with positions", lat_range, lon_range)

p_long_x_lat_platform1 <- get_loc_by_platform(summary_table_netcdf, "{{platform1}}") %>%
  create_region_scatter("Platform: {{platform1}}", lat_range, lon_range)

p_long_x_lat_platform2 <- get_loc_by_platform(summary_table_netcdf, "{{platform2}}") %>%
  create_region_scatter("Platform: {{platform2}}", lat_range, lon_range)

p_long_x_lat_platform3 <- get_loc_by_platform(summary_table_netcdf, "{{platform3}}") %>%
  create_region_scatter("Platform: {{platform3}}", lat_range, lon_range)

print(plot_grid(p_long_x_lat, p_long_x_lat_platform1,
                p_long_x_lat_platform2, p_long_x_lat_platform3, nrow = {{plot_nrow}}))

```

### Histograms of longitudes and latitudes from all profiles

```{r, t_summary_loc3, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}

p_long_dense <- summary_table_netcdf %>% mutate(x = longitude) %>%
  create_region_hist("Histogram of longitude", "Longitude")
p_lat_dense <- summary_table_netcdf %>% mutate(x = latitude) %>%
  create_region_hist("Histogram of latitude", "Latitude")

print(plot_grid(p_long_dense, p_lat_dense, nrow = 1))

```
