### Number of platforms, profiles, and observations
```{r, t_summary_desc_stats1, echo = FALSE, message = FALSE, warning = FALSE}
summary_table <- {{df}} %>%
  summarise(across(everything(), ~ typeof(.))) %>%
  t() %>% as.data.frame() %>%
  rownames_to_column("Variable") %>% as_tibble() %>%
  select(Variable, Type=2)

summary_table_netcdf <- netcdf_summary_1({{df}})
summary_table_netcdf2 <- netcdf_summary_2(summary_table_netcdf)
summary_loc_table <- netcdf_loc_summary(summary_table_netcdf2)

```

 - **Number of observations**: `r formatC(nrow({{df}}), big.mark=",")`
 - **Number of platform**: `r formatC(nrow(summary_table_netcdf2), big.mark=",")`
 - **Number of profiles**: `r formatC(sum(summary_table_netcdf2$profile_count), big.mark=",")`


### Summary statistics by profiles

```{r, t_summary_desc_stats2, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
summary_table_netcdf2 <- format_netcdf_summary_2(summary_table_netcdf2)
create_dt_summary_tab(summary_table_netcdf2)

```
