### NA value counts

```{r, t_var_stats1, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

df_filtered <- {{df}} %>% filter(!is.na({{var}}))
kbl_table(na_summary({{df}}, {{var}})) %>% kable_styling(font_size = 12)

```

### Descriptive statistics

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
df_ds <- df_filtered %>% mutate(x = {{var}})
min_var <- min(df_ds$x) %>% round(2)
max_var <- max(df_ds$x) %>% round(2)
mean_var <- mean(df_ds$x) %>% round(2)
median_var <- median(df_ds$x) %>% round(2)
q1_var <- quantile(df_ds$x, .25) %>% round(2)
q3_var <- quantile(df_ds$x, .75) %>% round(2)
sd_var <- sd(df_ds$x) %>% round(2)
```

  - `Min`: `r min_var`
  - `Q1`: `r q1_var`
  - `Median`: `r median_var`
  - `Mean`: `r mean_var`
  - `Q3`: `r q3_var`
  - `Max`: `r max_var`
  - `SD`: `r sd_var`

### Summary table of `r tolower("{{var_name}}")` by platform

```{r, t_var_stats2, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

summary_table_var1 <- var_summary_1(df_filtered, {{var}})
create_dt_summary_tab(summary_table_var1 %>% format_var_summary_1("{{var_label}}"),
                      cols=c('Min({{var_label}})', 'Median({{var_label}})',
                             'Mean({{var_label}})', 'Max({{var_label}})'))

```
