```{r, t_var_dist_year1, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

summary_table_var3 <- var_summary_2(df_filtered, "{{var}}")
summary_table_var3_qc1 <- var_summary_2(df_filtered_qc1, "{{var}}")
summary_table_var3_qc4 <- var_summary_2(df_filtered_qc4, "{{var}}")

df_year <- summary_table_var3 %>%
  mutate(x = format(profile_timestamp, "%Y"))

df_year_qc1 <- summary_table_var3_qc1 %>%
  mutate(x = format(profile_timestamp, "%Y"))

df_year_qc4 <- summary_table_var3_qc4 %>%
  mutate(x = format(profile_timestamp, "%Y"))

```

::: {.panelset}
::: {.panel}

### All

```{r, t_var_dist_year2, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 10}
p_year_bp <- create_var_boxplot(df_year, "{{var_name}}")

print(p_year_bp)
```

:::

::: {.panel}

### Good (QC == 1)

```{r, t_var_dist_year3, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 10}
p_year_bp_qc1 <- create_var_boxplot(df_year_qc1, "{{var_name}}")

print(p_year_bp_qc1)
```

:::

::: {.panel}

### Bad (QC == 4)

```{r, t_var_dist_year4, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 10}
p_year_bp_qc4 <- create_var_boxplot(df_year_qc4, "{{var_name}}")

print(p_year_bp_qc4)
```

:::
:::
