```{r, t_var_dist_month1, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

df_month <- summary_table_var3 %>%
  mutate(x = format(profile_timestamp, "%m"))

df_month_qc1 <- summary_table_var3_qc1 %>%
  mutate(x = format(profile_timestamp, "%m"))

df_month_qc4 <- summary_table_var3_qc4 %>%
  mutate(x = format(profile_timestamp, "%m"))

```

::: {.panelset}
::: {.panel}

### All

```{r, t_var_dist_month2, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 10}
p_month_bp <- create_var_boxplot(df_month, "{{var_name}}")

print(p_month_bp)
```

:::

::: {.panel}

### Good (QC == 1)

```{r, t_var_dist_month3, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 10}
p_month_bp_qc1 <- create_var_boxplot(df_month_qc1, "{{var_name}}")

print(p_month_bp_qc1)
```

:::

::: {.panel}

### Bad (QC == 4)

```{r, t_var_dist_month4, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 10}

if (nrow(df_year_qc4) > 0) {
  p_month_bp_qc4 <- create_var_boxplot(df_month_qc4, "{{var_name}}")
  print(p_month_bp_qc4)
} else {
  cat("No data available to display.")
}

```

:::
:::
